### PR TITLE
Fix WaveHeader covering AuthDialog

### LINKED ISSUE #170: [Bug] WaveHeader covers authentication dialog
### Expected Behavior

WaveHeader should not cover any of the main content. Resize this

### Steps to Reproduce

image

### Device Information

Desktop/Mobile: Desktop
OS: macOS Monterey 12.3.1
Browser Version: Safari 15.4

### PR DESCRIPTION
**Pull request by gramliu**
# Description

Closes #170 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [ ] Test A
- [ ] Test B

**Test Configuration**:

- Node.js version:
- Python version:
- Desktop/Mobile:
- OS:
- Browser:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by pm3512** [comment]
hm, I'm still getting the issue on small devices in landscape mode:
image
Mb we can just remove the header when the height is too small?

**Comment by gramliu** [comment]
Oh I did not test mobile landscape mode LOL do you think it's worth still supporting? I feel like most mobile users operate in portrait mode. We can nonetheless make this an issue for a future patch

**Comment by pm3512** [comment]
Sure, sounds good. For now, there's a small fix for landscape like this:
In styles/mixins.scss:
```
@mixin height-down($screen) {
  @media (max-height: $screen) {
    @content;
  }
}
```
In src/components/design/WaveHeader/index.module.scss:
```
.waveContainer {
  position: absolute;
  width: 100%;
  overflow: hidden;
  line-height: 0;
  @include height-down ($breakpoint-md) {
    display: none;
  }
}
```

The login page ends up looking like this: 
image

**Comment by gramliu** [comment]
Thanks 🙇 I'll use this

**Review by pm3512 — APPROVED** [review]

**Pull request merged**
